name: ci

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  policy:
    uses: hzr3d/arres_devops/.github/workflows/policy-ci.yml@main
    permissions:
      id-token: write  
    with:
      project_type: python_lib
      artifact_name: mock_lib
      run_integration: true
